#-Basic info----------------------------------------------------------------------------------------
name: run_launcher
version: 2.0.7
note: >
  Currently run components aren't set up properly (probably want to call them collection components)
  values here are not being used properly. I think the idea for run components is that you don't 
  compare run components against one another. They are contextual to themselves. Thus options here
  can be flexible compared to sample components which are designed to be compared to one another.
  Maybe this just needs to be named as two different types. One for comparison and one which is not 
  and in the case where its not meant to be compared the interesting thing about the component 
  (pipeline) as in this case is that it sets things up for others. Not that it creates an 
  interesting result on it's own
#---------------------------------------------------------------------------------------------------

#-Details-------------------------------------------------------------------------------------------
details:
  schema_version: 2.0.7
  target: run
  type: pipeline
  recommendation: recommended
  description: >
    Processes a folder for running in bifrost
#---------------------------------------------------------------------------------------------------

#-Docker location-----------------------------------------------------------------------------------
dockerfile: &dockerfile "docker://ssidk/bifrost-run_launcher:2.0.7"
#---------------------------------------------------------------------------------------------------

#-Options-------------------------------------------------------------------------------------------
options:
# None
#---------------------------------------------------------------------------------------------------

#-Required resource files---------------------------------------------------------------------------
resources:
# None
#---------------------------------------------------------------------------------------------------

#-Requirements to run component---------------------------------------------------------------------
requirements:
# Non-DB file requirements
#  files:
#    -samples_folder
#    -"run_metadata.tsv"
#    -"rename.json"
#    -"pre_script.sh"
#    -"per_sample_script.sh"
#    -"post_script.sh"
#---------------------------------------------------------------------------------------------------

#-DB Value changes (excluding component output)-----------------------------------------------------
db_values_changes:
  files: []
  run:
    # new run object
  sample:
    # a new sample object for each one in the run
#---------------------------------------------------------------------------------------------------
